CREATE TABLE PLAYER (
  PLAYER_ID NUMBER(10) not null,
  NAME VARCHAR(50) NOT NULL,
  AGE NUMBER(3) NOT NULL,
  MATCHES NUMBER(3) NOT NULL,
  CONSTRAINT pk_id PRIMARY KEY(PLAYER_ID)
);
commit;
INSERT INTO PLAYER(PLAYER_ID,NAME, AGE, MATCHES) VALUES (1,'Sachin Tendulkar',41,200);
INSERT INTO PLAYER(PLAYER_ID,NAME,AGE, MATCHES) VALUES (2,'Shane Warne',44,145);
INSERT INTO PLAYER(PLAYER_ID,NAME, AGE, MATCHES) VALUES (3,'Kevin Pietersen',34,104);
INSERT INTO PLAYER(PLAYER_ID,NAME, AGE, MATCHES) VALUES (4,'Shahid Afridi',35,27);
INSERT INTO PLAYER(PLAYER_ID,NAME, AGE, MATCHES) VALUES (5,'Brian Lara',45,131);
INSERT INTO PLAYER(PLAYER_ID,NAME, AGE, MATCHES) VALUES (6,'Graeme Smith',34,117);
INSERT INTO PLAYER(PLAYER_ID,NAME, AGE, MATCHES) VALUES (7,'Mahela Jayawardene',37,145);